Repository jenkinsci/junit-attachments-plugin, pull requests merged in 2022-03, with the labels that each got.

#28 Add `index.jelly` with plugin description
  src/main/resources/index.jelly
Labels: documentation

#29 Add symbol for attachments publishers and modernize test
  src/main/java/hudson/plugins/junitattachments/AttachmentPublisher.java
  src/test/resources/hudson/plugins/junitattachments/pipelineTest.groovy
Labels: enhancement

#30 Enable CD
  .github/dependabot.yml
  .github/release-drafter.yml
  .github/workflows/cd.yaml
  .mvn/maven.config
  pom.xml
Labels: chore
