Repository jenkinsci/junit-attachments-plugin, pull requests merged in 2022-05, with the labels that each got.

#39 Use modern `jenkins-table` to list attachments
  pom.xml
  src/main/resources/hudson/plugins/junitattachments/AttachmentTestAction/summary.jelly
Labels: enhancement

#38 Make a comment more inclusive
  src/main/java/hudson/plugins/junitattachments/GetTestDataMethodObject.java
Labels: chore

#40 Revert baseline to 2.332.1
  pom.xml
Labels: developer
