Repository jenkinsci/junit-attachments-plugin, pull requests merged in 2025-03, with the labels that each got.

#154 bug: Correct hrefs for attachments in Standard Output (#153)
  src/main/java/hudson/plugins/junitattachments/AttachmentTestAction.java
Labels: bug

#157 Add option to show/not show attachments at test class level (#156)
  src/main/java/hudson/plugins/junitattachments/AttachmentPublisher.java
  src/main/resources/hudson/plugins/junitattachments/AttachmentPublisher/config.jelly
Labels: enhancement

#159 Migrate tests to JUnit5
  src/test/java/hudson/plugins/junitattachments/AttachmentPublisherPipelineTest.java
  src/test/java/hudson/plugins/junitattachments/AttachmentPublisherTest.java
Labels: tests

#160 Process attachments by test case not class (#156)
  src/main/java/hudson/plugins/junitattachments/AttachmentPublisher.java
  src/main/java/hudson/plugins/junitattachments/AttachmentTestAction.java
  src/main/java/hudson/plugins/junitattachments/GetTestDataMethodObject.java
  src/main/java/hudson/plugins/junitattachments/TestCaseAttachmentTestAction.java
  src/main/java/hudson/plugins/junitattachments/TestClassAttachmentTestAction.java
  src/main/resources/hudson/plugins/junitattachments/TestCaseAttachmentTestAction/summary.jelly
  src/main/resources/hudson/plugins/junitattachments/TestClassAttachmentTestAction/summary.jelly
  src/test/java/hudson/plugins/junitattachments/AttachmentPublisherPipelineTest.java
  src/test/java/hudson/plugins/junitattachments/AttachmentPublisherTest.java
Labels: enhancement
